services:
  blog:
    build: .
    container_name: lukeblaney_blog
    ports:
      - $PORT:80
    image: lucas42/lukeblaney_blog:${VERSION:-latest}
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:80/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
